from enum import Enum


class EstadoAgente(str, Enum):
    INICIO = "INICIO"
    LEER_HISTORIAL = "LEER_HISTORIAL"
    ANALIZAR_INTENCION = "ANALIZAR_INTENCION"
    DECIDIR_HERRAMIENTA = "DECIDIR_HERRAMIENTA"
    EJECUTAR_HERRAMIENTA = "EJECUTAR_HERRAMIENTA"
    GENERAR_RESPUESTA = "GENERAR_RESPUESTA"
    FINALIZAR = "FINALIZAR"


TRANSICIONES_AGENT_LOOP: dict[EstadoAgente, EstadoAgente] = {
    EstadoAgente.INICIO: EstadoAgente.LEER_HISTORIAL,
    EstadoAgente.LEER_HISTORIAL: EstadoAgente.ANALIZAR_INTENCION,
    EstadoAgente.ANALIZAR_INTENCION: EstadoAgente.DECIDIR_HERRAMIENTA,
    EstadoAgente.DECIDIR_HERRAMIENTA: EstadoAgente.EJECUTAR_HERRAMIENTA,
    EstadoAgente.EJECUTAR_HERRAMIENTA: EstadoAgente.GENERAR_RESPUESTA,
    EstadoAgente.GENERAR_RESPUESTA: EstadoAgente.FINALIZAR,
}
